name: Build Manifest

on:
  push:
    paths:
      - "songs/*.cbs"
      - ".github/workflows/manifest.yml"
      - "generate_manifest.py"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run generator
        run: python generate_manifest.py

      - name: Commit & push manifest
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add manifest.json
          git commit -m "update manifest [ci skip]" || echo "no changes"
          git push
